### ISSUE TITLE
Actor/Studio metadata broken

### ISSUE THREAD

**Issue by justindmyers** [imaginary-upside/JellyfinJav#12]
Not sure what's happening but with a brand new install of Jellyfin 10.71 and JellyfinJav, no actor or studio metadata is being generated but the video itself is showing the actor/studio. Subsequently, clicking on the actor link throws an error and shows a blank screen.

Example:
The actor name appears correctly and gives a link:
![Screenshot 2021-03-26 180159](https://user-images.githubusercontent.com/58646/112705761-3021cb80-8e6e-11eb-99a1-70c339a24585.png)

But after clicking, Jellyfin throws a console error and goes to a blank screen.
![Screenshot 2021-03-26 180135](https://user-images.githubusercontent.com/58646/112705763-32842580-8e6e-11eb-80b8-bf6397963c70.png)

The studio and actor do show up in the metadata when editing in the UI, so I'm not sure why the links to them are broken.

![Screenshot 2021-03-26 193606](https://user-images.githubusercontent.com/58646/112707720-4aae7180-8e7b-11eb-9818-dc4b6b036739.png)

**Comment by justindmyers** [comment]
So a small update. I added a new library and only one actress page seemed to work (AIKA). No other actresses in that library worked.

**Comment by imaginary-upside** [comment]
The actress issue seems to me to be on Jellyfin's side, see here: https://github.com/jellyfin/jellyfin/issues/5493. Though it's odd that AIKA worked for you, as I tested ABG-006 and got the same issue. Could you send a screenshot of the video + actress page for her?

**Comment by imaginary-upside** [comment]
I've pushed version 2021.04.04 which fixes this.
