### ISSUE TITLE
 How can I display a number in the title?

### ISSUE THREAD

**Issue by srgtang** [imaginary-upside/JellyfinJav#7]
How can I display a number in the title?

ex) **MIDE-726** Infinite Piston Squirting Screaming Acme Sober Big Breasts Who Came To A Part-time Job Interview At An Imported General Store Do Not Escape By Wearing Obscenity Products With Bare Tits! Minamata Sakura

How can i display  **bold** ?

My jellyfin shows next. except **bold**

Infinite Piston Squirting Screaming Acme Sober Big Breasts Who Came To A Part-time Job Interview At An Imported General Store Do Not Escape By Wearing Obscenity Products With Bare Tits! Minamata Sakura

**Comment by imaginary-upside** [comment]
Hey, thanks for mentioning this. I added a commit which lets you customize how the title is displayed. I'll push out an update later.

**Comment by srgtang** [comment]
Can you delete my issue? I wanna delete github account.
